# Auto-generated by renv
# Do not edit by hand

# Load renv if available
if (interactive() || !identical(Sys.getenv("R_ENVIRON_USER"), "")) {
  if (file.exists(Sys.getenv("R_RENV_PATH", "renv/activate.R"))) {
    source(Sys.getenv("R_RENV_PATH", "renv/activate.R"))
  }
}
